---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mfs-website-frontend
  name: mfs-website-frontend-deployment
  namespace: NAMESPACE
spec:
  selector:
    matchLabels:
      app: mfs-website-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: mfs-website-frontend
    spec:
      volumes:
        - name: timezone-configuration
          hostPath:
            path: /usr/share/zoneinfo/Africa/Nairobi
      containers:
        - name: mfs-website-frontend
          image: ImageName
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: timezone-configuration
              mountPath: /etc/localtime
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - 10.38.83.215
          - 8.8.8.8

---
apiVersion: v1
kind: Service
metadata:
  name: mfs-website-frontend-service
  namespace: NAMESPACE
  labels:
    run: mfs-website-frontend-service
spec:
  type: NodePort
  ports:
    - name: mfs-website-frontend-port
      port: 80
      protocol: TCP
  selector:
    app: mfs-website-frontend
